### PR TITLE
update cats effect to 3

### PR DESCRIPTION
**Pull request by gipeshka**
Brings dependency up to date. The cats effect 3 looks backwards incompatible, so it probably would make sense to update these.

### CODE REVIEW

**Comment by gipeshka** [comment]
@dilyand not sure if this repo is still maintained, pinging you as the last one who merged a PR here.

**Comment by dilyand** [comment]
@gipeshka Many thanks for this PR, it's much appreciated!

Our main use for this library is as part of [Enrich](https://github.com/snowplow/enrich) where unfortunately we have other dependencies that are not yet CE3 ready, such as [scalacache](https://github.com/cb372/scalacache). But that doesn't prevent us from releasing a new version of this library -- it just means that Enrich will have to continue using the old version until we can migrate safely.

I've raised this internally, to put this release on the roadmap. Hopefully we'll be able to address this PR sooner rather than later.

Just out of curiosity, do you have use for `scala-referer-parser` outside of Enrich?

**Comment by gipeshka** [comment]
hey @dilyand, yeah, we're using the referer parser directly.

**Comment by gipeshka** [comment]
> I've raised this internally, to put this release on the roadmap

@dilyand do you have any estimation on a release date for this update?

**Comment by pondzix** [comment]
Closing in favour of https://github.com/snowplow-referer-parser/scala-referer-parser/pull/125

**Pull request closed without merging**
