### PR TITLE
Bump to scala 2.13.3 (closes #98)

### LINKED ISSUE #98: Bump Scala to 2.13.3

### PR DESCRIPTION
**Pull request by sriraamas**

### CODE REVIEW

**Comment by sriraamas** [comment]
@alexanderdean  I am hoping to have a scala-213 release for scala-referer-parser, so we can migrate all of our codebase that uses this library to scala 2.13.  

Thanks for your help in advance!

**Comment by sriraamas** [comment]
We are currently in the middle of migration to scala 2.13. If we can have a release of this sooner, rather than later, that would be most helpful.

**Comment by sriraamas** [comment]
@melgenek @lstrojny @ujali @alexanderdean @chuwy  Any chance we can have a release for this?

**Comment by lstrojny** [comment]
@sriraamas "not my department"

**Comment by ujali** [comment]
@sriraamas, we also need this release since we are also migrating our project to Scala 2.13. I did send out an email to Alex Dean regarding this last week and he looped in his VP eng.

**Comment by goodits** [comment]
Hi all. Sorry for the radio silence. We are looking to work this in to our upcoming schedule. Will post back with an ETA when we have one.

**Comment by lukeindykiewicz** [comment]
The artifact for Scala referer parser has been released, please check the GH release page or discourse announcement: https://discourse.snowplowanalytics.com/t/scala-referer-parser-1-1-0-released/4173

**Pull request merged**
