### PR TITLE
Reformat with scalafmt (close #102)

### LINKED ISSUE #102: Reformat with scalafmt

### PR DESCRIPTION
**Pull request by lukeindykiewicz**
Reformat with current (in the project) scalafmt -> this makes changes to 4 files. 
If we would change scalafmt config to our current standard it will change 16 files.

### CODE REVIEW

**Comment by benjben** [comment]
>  If we would change scalafmt config to our current standard it will change 16 files.
What's wrong with changing 4 files instead of 16 @lukeindykiewicz ?

**Comment by lukeindykiewicz** [comment]
@benjben  I just explained why I didn't change the scalafmt config to our latest version. The reason is it reformats a lot of files. Does it answer your question?

**Comment by lukeindykiewicz** [comment]
@oguzhanunlu Thanks for spotting. I don't know why it was like that - maybe because the base wasn't master.

**Comment by lukeindykiewicz** [comment]
It's rebased on master. I also foind that sbt files are not formatted, so I took the opportunity and added the `scalaSbtCheck` to travis and also reformatted the build files.

**Comment by lukeindykiewicz** [comment]
I also updated the scalafmt plugin version and config version to newest.

**Review by oguzhanunlu — APPROVED** [review]
Thanks @lukeindykiewicz !

**Comment by lukeindykiewicz** [comment]
According to what we have discussed, the `scalafmtOnCompile := true,` is removed. 
Also I copy-pasted the latest scalafmt config and reformatted the whole project. 
Also updated the copyright year.

**Review by dilyand — APPROVED** [review]
👍🏻

**Pull request merged**
